#!/usr/bin/env zsh

cd ~/Developer/agentk/dotties || exit 1

for FOLDER in ~/.dotfiles/*(/); do
  FOLDERNAME=${FOLDER:t}
  if [[ $FOLDERNAME == ssh || $FOLDERNAME == .git ]]; then
    continue
  fi
  rsync -avh --delete \
    --exclude secrets.decrypted.json \
    --exclude secrets.json \
    --exclude node_modules \
    "$HOME/.dotfiles/$FOLDERNAME/" \
    "$HOME/Developer/agentk/dotties/$FOLDERNAME/"
done
rsync -avh --delete "$HOME/.dotfiles/.githooks/" "$HOME/Developer/agentk/dotties/.githooks/"

for FILE in .editorconfig .prettierrc.yaml Brewfile Npmfile bootstrap modelsdev.json; do
  cp -v "$HOME/.dotfiles/$FILE" ~/Developer/agentk/dotties/$FILENAME
done

git add .
git commit --amend --no-edit
