#!/usr/bin/env zsh

cd ~/Developer/agentk/dotties || exit 1

for FOLDER in .cache .config .githooks .hammerspoon Library bin secrets resources; do
  rsync -avh --delete \
    --exclude secrets.decrypted.json \
    --exclude secrets.json \
    --exclude node_modules \
    "$HOME/.dotfiles/$FOLDER/" \
    "$HOME/Developer/agentk/dotties/$FOLDER/"
done

for FILE in .editorconfig .gitignore .prettierrc.yaml .yamllint Brewfile Npmfile bootstrap; do
  cp -v "$HOME/.dotfiles/$FILE" ~/Developer/agentk/dotties/$FILENAME
done

git add .
git commit --amend --no-edit
